#!/usr/bin/env python3
"""Render a self-contained static hub page from ``manifest.json``.

``manifest.json`` is a GENERATED COMPATIBILITY VIEW (see ``tools/build-manifest.py``)
— this script only READS it; it never hand-edits or regenerates ``manifest.json``
itself. Run ``tools/build-manifest.py`` (or ``tools/generate.py``) first if
``manifest.json`` is stale.

``hub.html`` is a single self-contained HTML file: the navigation-relevant slice of
``manifest.json`` (skills, agents, hooks, loops, tracks, topology_registry summary)
is embedded as a ``<script type="application/json">`` block, and inline JS renders
the map + skill-catalog views and per-item detail from that embedded data. It must
open directly via ``file://`` with zero fetch/CDN/external-network calls. Operational
views (approval queue, memory) are out of scope by design — see the router task that
introduced this generator.

Determinism: no timestamps or randomness. The embedded payload is a straight,
order-preserving slice of the already-deterministic ``manifest.json`` (stable-sorted
upstream by ``tools/build-manifest.py``), and the surrounding HTML/CSS/JS shell is a
fixed string. Re-running produces a byte-identical ``hub.html``.

Usage:
  python3 tools/render-hub.py            # write hub.html at repo root
  python3 tools/render-hub.py --check    # render in memory, diff vs existing, exit 1 on drift
"""
from __future__ import annotations

import json
import os
import sys

# realpath (not abspath): this script is executed via the collapsed adapter symlink
# (adapters/claude/tools/render-hub.py -> ../../../tools/render-hub.py). abspath keeps
# the symlink path, resolving REPO_ROOT to repo/adapters/claude (double-path bug);
# realpath follows the link to the canonical tools/, giving the true repo root either way.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
MANIFEST_PATH = os.path.join(REPO_ROOT, "manifest.json")
HUB_PATH = os.path.join(REPO_ROOT, "hub.html")

# Hub scope: navigation/catalog data only. Operational (approval queue) and memory
# views are intentionally excluded, per the task that introduced this generator.
VIEW_FIELDS = (
    "generated_from",
    "manifest_version",
    "topology_registry",
    "skills",
    "agents",
    "hooks",
    "loops",
    "tracks",
)

DATA_PLACEHOLDER = "__HUB_DATA_JSON__"


def load_manifest():
    if not os.path.exists(MANIFEST_PATH):
        sys.stderr.write(
            "manifest.json missing — run `python3 tools/build-manifest.py` first\n"
        )
        sys.exit(2)
    with open(MANIFEST_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def build_view(manifest):
    """Slice manifest.json down to the hub page's scope. Field/list order is
    preserved exactly as in manifest.json (already stable-sorted upstream), so
    this stays a pure, deterministic projection — no re-sorting or re-shaping."""
    missing = [field for field in VIEW_FIELDS if field not in manifest]
    if missing:
        sys.stderr.write(
            "manifest.json missing expected field(s): %s\n" % ", ".join(missing)
        )
        sys.exit(2)
    return {field: manifest[field] for field in VIEW_FIELDS}


def _embed_json(data):
    text = json.dumps(data, ensure_ascii=False, indent=2, sort_keys=False)
    # Never let embedded data terminate the surrounding <script> element early.
    return text.replace("</", "<\\/")


PAGE_TEMPLATE = """<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>에이전트 허브</title>
<!--
  GENERATED by tools/render-hub.py — DO NOT EDIT BY HAND.
  Source: manifest.json (generated compatibility view; canonical: harness-manifest.json).
  Self-contained: no fetch/CDN/network. Data is embedded as JSON below; inline JS
  renders the DOM from it. Regenerate: python3 tools/render-hub.py
  Verify:     python3 tools/render-hub.py --check
-->
<style>
  :root {
    color-scheme: light dark;
    --bg: #ffffff;
    --fg: #18181b;
    --muted: #6b7280;
    --card-bg: #f8fafc;
    --card-border: #e2e8f0;
    --accent: #2563eb;
    --code-bg: #f1f5f9;
    --panel-bg: #ffffff;
    --panel-shadow: 0 8px 32px rgb(0 0 0 / 0.18);
    --cat-1: #2563eb;
    --cat-2: #059669;
    --cat-3: #d97706;
    --cat-4: #7c3aed;
    --cat-5: #db2777;
    --cat-6: #0891b2;
    --cat-7: #dc2626;
    --cat-8: #4b5563;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #0b0f19;
      --fg: #e5e7eb;
      --muted: #9ca3af;
      --card-bg: #131826;
      --card-border: #262f42;
      --accent: #60a5fa;
      --code-bg: #0f1420;
      --panel-bg: #131826;
      --panel-shadow: 0 8px 32px rgb(0 0 0 / 0.5);
      --cat-1: #60a5fa;
      --cat-2: #34d399;
      --cat-3: #fbbf24;
      --cat-4: #a78bfa;
      --cat-5: #f472b6;
      --cat-6: #22d3ee;
      --cat-7: #f87171;
      --cat-8: #d1d5db;
    }
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    background: var(--bg);
    color: var(--fg);
    font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    line-height: 1.55;
  }
  header.hub-header {
    padding: 24px clamp(16px, 4vw, 48px) 12px;
    border-bottom: 1px solid var(--card-border);
  }
  header.hub-header h1 { margin: 0 0 6px; font-size: 1.6rem; }
  .hub-meta { color: var(--muted); font-size: 0.85rem; }
  .hub-meta code { background: var(--code-bg); border-radius: 4px; padding: 1px 5px; }
  nav.hub-tabs {
    display: flex; gap: 8px; margin-top: 14px;
  }
  nav.hub-tabs button {
    font: inherit; cursor: pointer;
    border: 1px solid var(--card-border);
    background: var(--card-bg); color: var(--fg);
    border-radius: 999px; padding: 6px 16px;
  }
  nav.hub-tabs button[aria-pressed="true"] {
    background: var(--accent); color: #ffffff; border-color: var(--accent);
  }
  main { padding: 20px clamp(16px, 4vw, 48px) 80px; }
  section.hub-view[hidden] { display: none; }
  section.hub-view h2 {
    font-size: 1.15rem; margin: 28px 0 10px; padding-top: 8px;
    border-top: 1px solid var(--card-border);
  }
  section.hub-view h2:first-of-type { border-top: none; margin-top: 0; }
  .stat-strip {
    display: flex; flex-wrap: wrap; gap: 10px; margin: 10px 0 4px;
  }
  .stat-chip {
    background: var(--card-bg); border: 1px solid var(--card-border);
    border-radius: 8px; padding: 6px 12px; font-size: 0.85rem;
  }
  .stat-chip b { font-variant-numeric: tabular-nums; }
  .track { margin-bottom: 18px; border-left: 4px solid var(--track-color, var(--accent)); padding-left: 12px; }
  .track-title { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }
  .track-title h3 { margin: 0; font-size: 1rem; }
  .track-title code { color: var(--muted); font-size: 0.8rem; }
  .flow { display: flex; align-items: center; flex-wrap: wrap; gap: 6px; margin: 8px 0; }
  .flow-node {
    font: inherit; cursor: pointer; text-align: left;
    border: 1px solid var(--card-border); background: var(--card-bg); color: var(--fg);
    border-radius: 6px; padding: 6px 10px; font-size: 0.85rem;
  }
  .flow-node:hover { border-color: var(--track-color, var(--accent)); }
  .flow-arrow { color: var(--muted); }
  .track-gates { color: var(--muted); font-size: 0.8rem; }
  .card-grid {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
    gap: 10px; margin: 8px 0;
  }
  .mini-card {
    font: inherit; cursor: pointer; text-align: left;
    border: 1px solid var(--card-border); background: var(--card-bg); color: var(--fg);
    border-radius: 8px; padding: 10px 12px;
  }
  .mini-card:hover { border-color: var(--accent); }
  .mini-card .mini-title { font-weight: 600; margin-bottom: 4px; }
  .mini-card .mini-blurb { color: var(--muted); font-size: 0.82rem; }
  .badge-row { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 6px; }
  .badge {
    font-size: 0.72rem; background: var(--code-bg); color: var(--muted);
    border-radius: 999px; padding: 1px 8px;
  }
  .badge.warn { background: #7c2d12; color: #fed7aa; }
  .hook-event-group { margin-bottom: 14px; }
  .hook-event-group h3 { margin: 0 0 6px; font-size: 0.95rem; color: var(--muted); }
  .group-block { margin-bottom: 22px; }
  .group-block > .group-heading { font-size: 0.95rem; color: var(--muted); margin: 0 0 8px; }
  .group-heading code { color: var(--fg); background: var(--code-bg); border-radius: 4px; padding: 1px 6px; }
  .skill-card {
    border: 1px solid var(--card-border); background: var(--card-bg); border-radius: 10px;
    padding: 12px 14px; margin-bottom: 10px;
  }
  .skill-card-toggle {
    all: unset; cursor: pointer; display: block; width: 100%;
  }
  .skill-card-name { font-weight: 600; font-size: 1rem; }
  .skill-card-slug { color: var(--muted); font-size: 0.78rem; margin-left: 6px; }
  .field-label { color: var(--muted); font-size: 0.78rem; margin: 8px 0 2px; }
  .field-value { font-size: 0.88rem; }
  .field-value code {
    background: var(--code-bg); border-radius: 4px; padding: 1px 6px; font-size: 0.82rem;
  }
  .skill-card-detail { margin-top: 6px; }
  .skill-card-detail[hidden] { display: none; }
  #detail-panel {
    position: fixed; right: 0; top: 0; bottom: 0; width: min(360px, 92vw);
    background: var(--panel-bg); box-shadow: var(--panel-shadow);
    border-left: 1px solid var(--card-border);
    padding: 16px; overflow-y: auto; transform: translateX(100%);
    transition: transform 0.15s ease-out;
  }
  #detail-panel.open { transform: translateX(0); }
  #detail-panel h3 { margin: 0 0 4px; }
  #detail-panel table { border-collapse: collapse; width: 100%; margin-top: 10px; }
  #detail-panel th, #detail-panel td {
    text-align: left; vertical-align: top; font-size: 0.82rem;
    padding: 4px 6px; border-bottom: 1px solid var(--card-border);
  }
  #detail-panel th { color: var(--muted); font-weight: 500; width: 34%; white-space: nowrap; }
  #detail-close {
    all: unset; cursor: pointer; float: right; color: var(--muted); font-size: 0.85rem;
  }
  footer.hub-footer {
    color: var(--muted); font-size: 0.75rem; text-align: center; padding: 12px;
    border-top: 1px solid var(--card-border);
  }
</style>
</head>
<body>
<header class="hub-header">
  <h1>에이전트 허브</h1>
  <div class="hub-meta" id="hub-meta"></div>
  <nav class="hub-tabs">
    <button type="button" id="tab-map" aria-pressed="true">지도</button>
    <button type="button" id="tab-catalog" aria-pressed="false">스킬 카탈로그</button>
  </nav>
</header>
<main>
  <section class="hub-view" id="view-map"></section>
  <section class="hub-view" id="view-catalog" hidden></section>
</main>
<aside id="detail-panel" aria-hidden="true"></aside>
<footer class="hub-footer">자동 생성됨 · tools/render-hub.py · 직접 수정하지 마세요</footer>
<script type="application/json" id="hub-data">
__HUB_DATA_JSON__
</script>
<script>
(function () {
  "use strict";
  var DATA = JSON.parse(document.getElementById("hub-data").textContent);

  function el(tag, attrs, children) {
    var node = document.createElement(tag);
    attrs = attrs || {};
    for (var key in attrs) {
      if (!Object.prototype.hasOwnProperty.call(attrs, key)) continue;
      if (key === "class") node.className = attrs[key];
      else if (key === "text") node.textContent = attrs[key];
      else node.setAttribute(key, attrs[key]);
    }
    (children || []).forEach(function (child) {
      if (child === null || child === undefined) return;
      node.appendChild(typeof child === "string" ? document.createTextNode(child) : child);
    });
    return node;
  }

  function orEmpty(value) {
    if (Array.isArray(value)) return value.length ? value.join(", ") : "—";
    if (value === null || value === undefined || value === "") return "—";
    return String(value);
  }

  function badgeRow(values) {
    var row = el("div", { class: "badge-row" }, []);
    (values || []).forEach(function (value) {
      row.appendChild(el("span", { class: "badge", text: value }, []));
    });
    return row;
  }

  function fieldBlock(label, valueNode) {
    var wrap = document.createDocumentFragment();
    wrap.appendChild(el("div", { class: "field-label", text: label }, []));
    wrap.appendChild(valueNode);
    return wrap;
  }

  function textField(label, value) {
    return fieldBlock(label, el("div", { class: "field-value", text: orEmpty(value) }, []));
  }

  function codeField(label, value) {
    var code = el("code", { text: orEmpty(value) }, []);
    return fieldBlock(label, el("div", { class: "field-value" }, [code]));
  }

  // Generic per-item detail panel: dumps every field of the clicked item so no
  // per-kind field list needs to be hardcoded here.
  var panel = document.getElementById("detail-panel");
  function hideDetail() {
    panel.classList.remove("open");
    panel.setAttribute("aria-hidden", "true");
  }
  function showDetail(kindLabel, item) {
    while (panel.firstChild) panel.removeChild(panel.firstChild);
    panel.appendChild(el("button", { id: "detail-close", type: "button", text: "닫기" }, []));
    panel.appendChild(el("h3", { text: item.name || item.id || item.slug || kindLabel }, []));
    panel.appendChild(el("div", { class: "hub-meta", text: kindLabel }, []));
    var table = el("table", {}, []);
    Object.keys(item).forEach(function (key) {
      var raw = item[key];
      var value = Array.isArray(raw) ? raw.join(", ") : (raw && typeof raw === "object" ? JSON.stringify(raw) : String(raw));
      var row = el("tr", {}, [
        el("th", { text: key }, []),
        el("td", { text: value === "" ? "—" : value }, []),
      ]);
      table.appendChild(row);
    });
    panel.appendChild(table);
    panel.classList.add("open");
    panel.setAttribute("aria-hidden", "false");
    document.getElementById("detail-close").addEventListener("click", hideDetail);
  }

  function groupInOrder(list, keyFn) {
    var order = [];
    var buckets = {};
    list.forEach(function (item) {
      var key = keyFn(item);
      if (!Object.prototype.hasOwnProperty.call(buckets, key)) {
        buckets[key] = [];
        order.push(key);
      }
      buckets[key].push(item);
    });
    return order.map(function (key) { return [key, buckets[key]]; });
  }

  function renderMeta() {
    var meta = document.getElementById("hub-meta");
    var reg = DATA.topology_registry || {};
    var parts = [
      "manifest_version " + orEmpty(DATA.manifest_version),
      "skills " + DATA.skills.length,
      "agents " + DATA.agents.length,
      "hooks " + DATA.hooks.length,
      "loops " + DATA.loops.length,
      "tracks " + DATA.tracks.length,
    ];
    meta.appendChild(el("div", { text: DATA.generated_from }, []));
    meta.appendChild(el("div", { text: parts.join(" · ") }, []));
  }

  function renderTracks(container) {
    container.appendChild(el("h2", { text: "트랙" }, []));
    var skillBySlug = {};
    DATA.skills.forEach(function (skill) { skillBySlug[skill.slug] = skill; });
    DATA.tracks.forEach(function (track) {
      var section = el("div", { class: "track" }, []);
      section.style.setProperty("--track-color", "var(" + track.color_token + ")");
      var titleRow = el("div", { class: "track-title" }, [
        el("h3", { text: track.label }, []),
        el("code", { text: track.id }, []),
      ]);
      section.appendChild(titleRow);
      var flow = el("div", { class: "flow" }, []);
      track.steps.forEach(function (slug, index) {
        var skill = skillBySlug[slug];
        var node = el("button", { type: "button", class: "flow-node", text: skill ? skill.name : slug }, []);
        node.addEventListener("click", function () {
          showDetail("스킬 · " + track.label, skill || { slug: slug });
        });
        flow.appendChild(node);
        if (index < track.steps.length - 1) {
          flow.appendChild(el("span", { class: "flow-arrow", text: "→" }, []));
        }
      });
      section.appendChild(flow);
      if (track.gates && track.gates.length) {
        section.appendChild(el("div", { class: "track-gates", text: "게이트: " + track.gates.join(", ") }, []));
      }
      container.appendChild(section);
    });
  }

  function renderAgents(container) {
    container.appendChild(el("h2", { text: "에이전트" }, []));
    var grid = el("div", { class: "card-grid" }, []);
    DATA.agents.forEach(function (agent) {
      var card = el("button", { type: "button", class: "mini-card" }, [
        el("div", { class: "mini-title", text: agent.name }, []),
        el("div", { class: "mini-blurb", text: agent.blurb }, []),
        badgeRow(agent.modes),
      ]);
      card.addEventListener("click", function () { showDetail("에이전트", agent); });
      grid.appendChild(card);
    });
    container.appendChild(grid);
  }

  function renderHooks(container) {
    container.appendChild(el("h2", { text: "훅" }, []));
    groupInOrder(DATA.hooks, function (hook) { return hook.event; }).forEach(function (pair) {
      var event = pair[0], hooks = pair[1];
      var group = el("div", { class: "hook-event-group" }, [el("h3", { text: event }, [])]);
      var grid = el("div", { class: "card-grid" }, []);
      hooks.forEach(function (hook) {
        var badges = [hook.mono];
        if (hook.hard_block) badges.push("hard_block");
        var card = el("button", { type: "button", class: "mini-card" }, [
          el("div", { class: "mini-title", text: hook.name }, []),
          badgeRow(badges),
        ]);
        card.addEventListener("click", function () { showDetail("훅", hook); });
        grid.appendChild(card);
      });
      group.appendChild(grid);
      container.appendChild(group);
    });
  }

  function renderLoops(container) {
    container.appendChild(el("h2", { text: "루프" }, []));
    var grid = el("div", { class: "card-grid" }, []);
    DATA.loops.forEach(function (loop) {
      var card = el("button", { type: "button", class: "mini-card" }, [
        el("div", { class: "mini-title", text: loop.name }, []),
        el("div", { class: "mini-blurb", text: loop.blurb }, []),
        badgeRow([loop.type, loop.layer].filter(Boolean)),
      ]);
      card.addEventListener("click", function () { showDetail("루프", loop); });
      grid.appendChild(card);
    });
    container.appendChild(grid);
  }

  function renderRegistry(container) {
    container.appendChild(el("h2", { text: "토폴로지 레지스트리" }, []));
    var reg = DATA.topology_registry || {};
    var strip = el("div", { class: "stat-strip" }, []);
    var stats = [
      ["출처", reg.source],
      ["다이제스트", reg.digest],
      ["역량", reg.capabilities],
      ["레시피", reg.recipes],
    ];
    stats.forEach(function (pair) {
      strip.appendChild(el("span", { class: "stat-chip", text: pair[0] + ": " + orEmpty(pair[1]) }, []));
    });
    container.appendChild(strip);
  }

  function renderMap() {
    var container = document.getElementById("view-map");
    renderTracks(container);
    renderAgents(container);
    renderHooks(container);
    renderLoops(container);
    renderRegistry(container);
  }

  function renderCatalog() {
    var container = document.getElementById("view-catalog");
    groupInOrder(DATA.skills, function (skill) { return skill.group; }).forEach(function (pair) {
      var group = pair[0], skills = pair[1];
      var block = el("div", { class: "group-block" }, [
        el("div", { class: "group-heading" }, ["그룹: ", el("code", { text: group }, [])]),
      ]);
      skills.forEach(function (skill) {
        var detail = el("div", { class: "skill-card-detail", hidden: "hidden" }, [
          textField("패밀리", skill.fam),
          textField("호출 방식", skill.invocation_class),
          codeField("슬러그", skill.slug),
        ]);
        var toggle = el("button", { type: "button", class: "skill-card-toggle", "aria-expanded": "false" }, [
          el("span", { class: "skill-card-name", text: skill.name }, []),
          el("span", { class: "skill-card-slug", text: skill.slug }, []),
          badgeRow(skill.modes),
          textField("설명", skill.blurb),
          textField("사용 시점", skill.use_when),
          textField("제외 대상", skill.not_for),
          codeField("인자 힌트", skill.argument_hint),
        ]);
        toggle.addEventListener("click", function () {
          var expanded = toggle.getAttribute("aria-expanded") === "true";
          toggle.setAttribute("aria-expanded", String(!expanded));
          if (expanded) detail.setAttribute("hidden", "hidden");
          else detail.removeAttribute("hidden");
        });
        var card = el("div", { class: "skill-card" }, [toggle, detail]);
        block.appendChild(card);
      });
      container.appendChild(block);
    });
  }

  function activateTab(name) {
    var mapView = document.getElementById("view-map");
    var catalogView = document.getElementById("view-catalog");
    var mapTab = document.getElementById("tab-map");
    var catalogTab = document.getElementById("tab-catalog");
    var showMap = name === "map";
    mapView.hidden = !showMap;
    catalogView.hidden = showMap;
    mapTab.setAttribute("aria-pressed", String(showMap));
    catalogTab.setAttribute("aria-pressed", String(!showMap));
  }

  document.getElementById("tab-map").addEventListener("click", function () { activateTab("map"); });
  document.getElementById("tab-catalog").addEventListener("click", function () { activateTab("catalog"); });

  renderMeta();
  renderMap();
  renderCatalog();
})();
</script>
</body>
</html>
"""


def render(manifest):
    payload = _embed_json(build_view(manifest))
    return PAGE_TEMPLATE.replace(DATA_PLACEHOLDER, payload)


def main(argv):
    check = "--check" in argv
    manifest = load_manifest()
    text = render(manifest)
    if check:
        existing = ""
        if os.path.exists(HUB_PATH):
            with open(HUB_PATH, encoding="utf-8") as fh:
                existing = fh.read()
        if text != existing:
            sys.stderr.write("hub.html drift: run `python3 tools/render-hub.py`\n")
            return 1
        print("hub.html up-to-date")
        return 0
    with open(HUB_PATH, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s" % os.path.relpath(HUB_PATH, REPO_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
